{
 "title": "Java Chaincode Dashboard (chaincodeid jc:1)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Chaincode Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Duration (last 1 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "  rate(endorser_propsal_duration_sum{chaincode=\"java-fixed-asset:v1.0.0\"}[1m])/ rate(endorser_propsal_duration_count{chaincode=\"java-fixed-asset:v1.0.0\"}[1m])"
    }
   ]
  },
  {
   "title": "Average Duration (last 5 mins)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(endorser_propsal_duration_sum{chaincode=\"java-fixed-asset:v1.0.0\"}[5m])/ rate(endorser_propsal_duration_count{chaincode=\"java-fixed-asset:v1.0.0\"}[5m])"
    }
   ]
  },
  {
   "title": "Thread Pool Active Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cc_tx_pool{metric=\"active_count\"}"
    },
    { "expr": "tx_current_task_count" }
   ]
  },
  {
   "title": "Thread Pool Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cc_tx_pool{metric=\"current_queue_depth\"}"
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum(jvm_memory_bytes_used)", "legendFormat": "used" },
    {
     "expr": "sum(jvm_memory_bytes_committed)",
     "legendFormat": "committed"
    },
    { "expr": "sum(jvm_memory_bytes_max)", "legendFormat": "max" }
   ]
  }
 ]
}